
name: Cron Job

on:
  schedule:
    - cron: '*/2 * * * *' # Run every 5 minutes

jobs:
  cron:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Cron Job
        run: curl -X POST https://shtr.vercel.app/api/cron
